name: Demo Action
on: [push]
jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Show files
              run: ls -l
            - name: Add download and update Url to every file
              run: |
                for file in $(ls -1); do
                    echo "https://raw.githubusercontent.com/${{github.repository}}/main/$file"
                done