name: Demo Action
on: [push]
jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              
            - name: Create a zip file containing all the scripts
              run: |
                apt install zip -y
                zip -r scripts.zip .

            - name: Create release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                current_date=$(date +"%Y-%m-%d")
                gh release create "$current_date" \
                --title="$current_date" \
                --draft \
                scripts.zip
                